package com.flt.Common;

public class SQLConstants {
    public static String txnUserCartItems = "CREATE TABLE IF NOT EXISTS TXN_USER_CART_ITEMS (ID INTEGER PRIMARY KEY, "
            + " USER_ID TEXT,CATEGORY_ID TEXT,PRODUCT_ID TEXT,PRODUCT_NAME TEXT,PRODUCT_IMAGE TEXT,PRICE TEXT, DISCOUNT TEXT,ITEM_ADDED_DATETIME TEXT);";
}
