//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCredential
    {
        public int Id { get; set; }
        public string LoginId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ImeiNo { get; set; }
        public string Language { get; set; }
        public string LastLogin { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
